In [2]:
import numpy as np

In [3]:
red = np.array([[1,1], [1,2], [2,1], [2,2], [2,3], [4,3]])

expVecRed = np.array([[np.mean(red[:,0]), np.mean(red[:,1])]])
expVecRed = expVecRed.transpose()
print("Red's expected value is")
print(expVecRed)    

covMatRed = np.cov(red.transpose())
print("Red's covariance matrix is:")
print(covMatRed)

invCovRed = np.linalg.inv(covMatRed)
W_Red = -0.5 * invCovRed
print("W matrix of red is:")
print(W_Red)
wVec_Red = np.dot(invCovRed, expVecRed)
print("w of red is:")
print(wVec_Red)
w_Red_0 = -0.5 * np.dot(np.dot(expVecRed.transpose(),invCovRed),expVecRed) - 0.5 * np.log(np.linalg.det(covMatRed)) + np.log(6/11)
print("w_0 of red is:")
print(w_Red_0)


Red's expected value is
[[2.]
 [2.]]
Red's covariance matrix is:
[[1.2 0.6]
 [0.6 0.8]]
W matrix of red is:
[[-0.66666667  0.5       ]
 [ 0.5        -1.        ]]
w of red is:
[[0.66666667]
 [2.        ]]
w_0 of red is:
[[-3.01738966]]


In [4]:
blue = np.array([[-1,-1], [-1,-2], [-2,-1], [-3,1], [-3,-2]])

expVecBlue = np.array([[np.mean(blue[:,0]), np.mean(blue[:,1])]])
expVecBlue = expVecBlue.transpose()
print("Blue's expected value is")
print(expVecBlue)    

covMatBlue = np.cov(blue.transpose())
print("Blue's covariance matrix is:")
print(covMatBlue)

invCovBlue = np.linalg.inv(covMatBlue)
W_Blue = -0.5 * invCovBlue
print("W matrix of blue is:")
print(W_Blue)
wVec_Blue = np.dot(invCovBlue, expVecBlue)
print("w of blue is:")
print(wVec_Blue)
w_Blue_0 = -0.5 * np.dot(np.dot(expVecBlue.transpose(),invCovBlue),expVecBlue) - 0.5 * np.log(np.linalg.det(covMatBlue)) + np.log(5/11)
print("w_0 of blue is:")
print(w_Blue_0)

Blue's expected value is
[[-2.]
 [-1.]]
Blue's covariance matrix is:
[[ 1.  -0.5]
 [-0.5  1.5]]
W matrix of blue is:
[[-0.6 -0.2]
 [-0.2 -0.4]]
w of blue is:
[[-2.8]
 [-1.6]]
w_0 of blue is:
[[-4.50002914]]
